dist: xenial

language: python

matrix:
  fast_finish: false
  include:
  - env: TOX_ENV=py27-django111
    python: 2.7

  - env: TOX_ENV=py35-django20
    python: 3.5

  - env: TOX_ENV=py36-django111
    python: 3.6
  - env: TOX_ENV=py36-django20
    python: 3.6
  - env: TOX_ENV=py36-django21
    python: 3.6
  - env: TOX_ENV=py36-django22
    python: 3.6
#  - env: TOX_ENV=py36-django30
#    python: 3.6

  - env: TOX_ENV=py37-django20
    python: 3.7
  - env: TOX_ENV=py37-django21
    python: 3.7
  - env: TOX_ENV=py37-django22
    python: 3.7
#  - env: TOX_ENV=py37-django30
#    python: 3.7

  - env: TOX_ENV=py38-django20
    python: 3.8
  - env: TOX_ENV=py38-django21
    python: 3.8
  - env: TOX_ENV=py38-django22
    python: 3.8
#  - env: TOX_ENV=py38-django30
#    python: 3.8

install: pip install -r examples/requirements/testing.txt

script: travis_retry tox -e $TOX_ENV

after_success:
  - pip install coveralls
  - coveralls
